//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkSide.Strings.Resources.Aliases {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Aliases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Aliases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkSide.Strings.Resources.Aliases.Aliases", typeof(Aliases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero Rankings;Hero Ranks.
        /// </summary>
        public static string HERO_RANKING {
            get {
                return ResourceManager.GetString("HERO_RANKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iam.
        /// </summary>
        public static string I_AM {
            get {
                return ResourceManager.GetString("I_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches;Match Data.
        /// </summary>
        public static string MATCH {
            get {
                return ResourceManager.GetString("MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nopatches.
        /// </summary>
        public static string NO_PATCHES {
            get {
                return ResourceManager.GetString("NO_PATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency;Pong;RTT.
        /// </summary>
        public static string PING {
            get {
                return ResourceManager.GetString("PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpause.
        /// </summary>
        public static string RESUME {
            get {
                return ResourceManager.GetString("RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talents.
        /// </summary>
        public static string TALENTS {
            get {
                return ResourceManager.GetString("TALENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams;Pro.
        /// </summary>
        public static string TOP_TEAMS {
            get {
                return ResourceManager.GetString("TOP_TEAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who am i?.
        /// </summary>
        public static string WHO_AM_I {
            get {
                return ResourceManager.GetString("WHO_AM_I", resourceCulture);
            }
        }
    }
}
