//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkSide.Strings.Resources.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkSide.Strings.Resources.General.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} to Queue.
        /// </summary>
        public static string ADDED_TRACK_TO_QUEUE {
            get {
                return ResourceManager.GetString("ADDED_TRACK_TO_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} tracks to the queue.
        /// </summary>
        public static string ADDED_X_TRACKS_TO_QUEUE {
            get {
                return ResourceManager.GetString("ADDED_X_TRACKS_TO_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases.
        /// </summary>
        public static string ALIASES {
            get {
                return ResourceManager.GetString("ALIASES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am already sending Dota 2 updates in {0}. To stop use &apos;{1}&apos;.
        /// </summary>
        public static string ALREADY_SENDING_UPDATES {
            get {
                return ResourceManager.GetString("ALREADY_SENDING_UPDATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already tracking **{0}** ({1}) and are not a pro member so I cant let you track more than one Steam Profile.
        /// </summary>
        public static string ALREADY_TRACKING_USER_NO_PRO_STATUS {
            get {
                return ResourceManager.GetString("ALREADY_TRACKING_USER_NO_PRO_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assist.
        /// </summary>
        public static string ASSIST {
            get {
                return ResourceManager.GetString("ASSIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are suppose to pass in a parameter with this command. type &apos;help [command name]&apos; for help.
        /// </summary>
        public static string BAD_ARGUMENT_MESSAGE {
            get {
                return ResourceManager.GetString("BAD_ARGUMENT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Stats.
        /// </summary>
        public static string BOT_STATS {
            get {
                return ResourceManager.GetString("BOT_STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets Bot&apos;s stats.
        /// </summary>
        public static string BOT_STATS_DESCR {
            get {
                return ResourceManager.GetString("BOT_STATS_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Has Been Up For.
        /// </summary>
        public static string BOT_UP_FOR {
            get {
                return ResourceManager.GetString("BOT_UP_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is sorta broken so if you face any issues just &apos;{0}&apos; and &apos;{1}&apos; again..
        /// </summary>
        public static string BROKEN_COMMAND_WARNING {
            get {
                return ResourceManager.GetString("BROKEN_COMMAND_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant seek this track..
        /// </summary>
        public static string CANNOT_SEEK_TRACK {
            get {
                return ResourceManager.GetString("CANNOT_SEEK_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey {0}, here is a list of all my commands..
        /// </summary>
        public static string COMMAND_LIST_GREETING {
            get {
                return ResourceManager.GetString("COMMAND_LIST_GREETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;help [command-name]&apos; or &apos;help [module-name]&apos; for more information.
        /// </summary>
        public static string COMMAND_LIST_HELP_STRING {
            get {
                return ResourceManager.GetString("COMMAND_LIST_HELP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of commands under {0} module.
        /// </summary>
        public static string COMMANDS_UNDER_MODULE {
            get {
                return ResourceManager.GetString("COMMANDS_UNDER_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I couldn&apos;t find a command called *{0}*.
        /// </summary>
        public static string COULD_NOT_FIND_COMMAND {
            get {
                return ResourceManager.GetString("COULD_NOT_FIND_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find any team with that ID or name.
        /// </summary>
        public static string COULD_NOT_FIND_TEAM {
            get {
                return ResourceManager.GetString("COULD_NOT_FIND_TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can always use &apos;support&apos; command just in case you ever need help from my creator. He is always so ready to help..
        /// </summary>
        public static string CREATOR_SUPPORT_STRING {
            get {
                return ResourceManager.GetString("CREATOR_SUPPORT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Locale is: [{0}].
        /// </summary>
        public static string CURRENT_LOCALE {
            get {
                return ResourceManager.GetString("CURRENT_LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Member.
        /// </summary>
        public static string CURRENT_MEMBER {
            get {
                return ResourceManager.GetString("CURRENT_MEMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm it was hard to remember but I think I am knows as &apos;{0}&apos; in this Party..
        /// </summary>
        public static string CURRENT_PREFIX_MESSAGE {
            get {
                return ResourceManager.GetString("CURRENT_PREFIX_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Queue.
        /// </summary>
        public static string CURRENT_QUEUE {
            get {
                return ResourceManager.GetString("CURRENT_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day(s).
        /// </summary>
        public static string DAY_S {
            get {
                return ResourceManager.GetString("DAY_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death.
        /// </summary>
        public static string DEATH {
            get {
                return ResourceManager.GetString("DEATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Parameters under &apos;[]&apos; are mandatory and the ones under &apos;&lt;&gt;&apos; are optional.
        /// </summary>
        public static string DETAILED_HELP_FOOTER {
            get {
                return ResourceManager.GetString("DETAILED_HELP_FOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed stats.
        /// </summary>
        public static string DETAILED_STATS {
            get {
                return ResourceManager.GetString("DETAILED_STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OpenDota]({0}){1}[DotaBuff]({2}).
        /// </summary>
        public static string DETAILED_STATS_STRING {
            get {
                return ResourceManager.GetString("DETAILED_STATS_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string DURATION {
            get {
                return ResourceManager.GetString("DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load responses..
        /// </summary>
        public static string FAILED_TO_LOAD_RESPONSE {
            get {
                return ResourceManager.GetString("FAILED_TO_LOAD_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPM.
        /// </summary>
        public static string GPM {
            get {
                return ResourceManager.GetString("GPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our sad guy hasn&apos;t played dota in a while or his profile / dota client is private af.
        /// </summary>
        public static string HAVE_NOT_PLAYED_DOTA_OR_PROFILE_PRIVATE {
            get {
                return ResourceManager.GetString("HAVE_NOT_PLAYED_DOTA_OR_PROFILE_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help on *{0}* coming right up.
        /// </summary>
        public static string HELP_ON_COMMAND {
            get {
                return ResourceManager.GetString("HELP_ON_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero Name.
        /// </summary>
        public static string HERO_NAME {
            get {
                return ResourceManager.GetString("HERO_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour(s).
        /// </summary>
        public static string HOUR_S {
            get {
                return ResourceManager.GetString("HOUR_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to But But But I already know you as [{0}].
        /// </summary>
        public static string I_ALREADY_KNOW_YOU_AS {
            get {
                return ResourceManager.GetString("I_ALREADY_KNOW_YOU_AS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idk who {0} is but i&apos;ll be glad to meet {1} at &apos;{2} [steam ID].
        /// </summary>
        public static string I_DONT_KNOW_USER {
            get {
                return ResourceManager.GetString("I_DONT_KNOW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uhh I don&apos;t know you. Either tell me who you are or provide a steamID with this command..
        /// </summary>
        public static string I_DONT_KNOW_YOU {
            get {
                return ResourceManager.GetString("I_DONT_KNOW_YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I know {0} as [{1}].
        /// </summary>
        public static string I_KNOW_USER_AS_STEAM_NAME {
            get {
                return ResourceManager.GetString("I_KNOW_USER_AS_STEAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, I will send Dota 2 patches in this channel.
        /// </summary>
        public static string I_WILL_SEND_UPDATES_IN_THE_CHANNEL {
            get {
                return ResourceManager.GetString("I_WILL_SEND_UPDATES_IN_THE_CHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Response.
        /// </summary>
        public static string INVALID_RESPONSE {
            get {
                return ResourceManager.GetString("INVALID_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kills.
        /// </summary>
        public static string KILLS {
            get {
                return ResourceManager.GetString("KILLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Match Played.
        /// </summary>
        public static string LAST_MATCH {
            get {
                return ResourceManager.GetString("LAST_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Played.
        /// </summary>
        public static string LAST_PLAYED {
            get {
                return ResourceManager.GetString("LAST_PLAYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} UTC.
        /// </summary>
        public static string LAST_PLAYED_STRING {
            get {
                return ResourceManager.GetString("LAST_PLAYED_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League Name.
        /// </summary>
        public static string LEAGUE_NAME {
            get {
                return ResourceManager.GetString("LEAGUE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale Changed to : [{0}].
        /// </summary>
        public static string LOCALE_CHANGED {
            get {
                return ResourceManager.GetString("LOCALE_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale not found: [{0}].
        /// </summary>
        public static string LOCALE_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOCALE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        public static string LOSE_PAST {
            get {
                return ResourceManager.GetString("LOSE_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses.
        /// </summary>
        public static string LOSSES {
            get {
                return ResourceManager.GetString("LOSSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your choice.
        /// </summary>
        public static string MAKE_YOUR_CHOICE {
            get {
                return ResourceManager.GetString("MAKE_YOUR_CHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Match Data for {0} **\n {1}.
        /// </summary>
        public static string MATCH_DATA_STRING {
            get {
                return ResourceManager.GetString("MATCH_DATA_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchID.
        /// </summary>
        public static string MATCH_ID_STRING {
            get {
                return ResourceManager.GetString("MATCH_ID_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string MATCHES {
            get {
                return ResourceManager.GetString("MATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medal.
        /// </summary>
        public static string MEDAL {
            get {
                return ResourceManager.GetString("MEDAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Usage.
        /// </summary>
        public static string MEMORY_USAGE {
            get {
                return ResourceManager.GetString("MEMORY_USAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute(s).
        /// </summary>
        public static string MINUTE_S {
            get {
                return ResourceManager.GetString("MINUTE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Successful Heroes.
        /// </summary>
        public static string MOST_SUCCESS_HEROES {
            get {
                return ResourceManager.GetString("MOST_SUCCESS_HEROES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm looks like we have never met before. But don&apos;t you worry Ive arranged us a secret meeting at {0} [your account].
        /// </summary>
        public static string NEVER_MET_BEFORE {
            get {
                return ResourceManager.GetString("NEVER_MET_BEFORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dude never played doto.
        /// </summary>
        public static string NEVER_PLAYED_DOTA {
            get {
                return ResourceManager.GetString("NEVER_PLAYED_DOTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright Alright in the latest patch people here have to call me &apos;{0}&apos;..
        /// </summary>
        public static string NEW_PREFIX_MESSAGE {
            get {
                return ResourceManager.GetString("NEW_PREFIX_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice to meet you [{0}].
        /// </summary>
        public static string NICE_TO_MEET_USER {
            get {
                return ResourceManager.GetString("NICE_TO_MEET_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sad to see you go..
        /// </summary>
        public static string NO_PATCHES_MESSAGE {
            get {
                return ResourceManager.GetString("NO_PATCHES_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No summary for {0}.
        /// </summary>
        public static string NO_SUMMARY {
            get {
                return ResourceManager.GetString("NO_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NONE_STRING {
            get {
                return ResourceManager.GetString("NONE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now at.
        /// </summary>
        public static string NOW_AT {
            get {
                return ResourceManager.GetString("NOW_AT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now I know you as [{0}].
        /// </summary>
        public static string NOW_I_KNOW_YOU {
            get {
                return ResourceManager.GetString("NOW_I_KNOW_YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing.
        /// </summary>
        public static string NOW_PLAYING {
            get {
                return ResourceManager.GetString("NOW_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string PING {
            get {
                return ResourceManager.GetString("PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        public static string PLAYER_NAME {
            get {
                return ResourceManager.GetString("PLAYER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string PLAYERS {
            get {
                return ResourceManager.GetString("PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing {0} Now.
        /// </summary>
        public static string PLAYING_NOW {
            get {
                return ResourceManager.GetString("PLAYING_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Profile.
        /// </summary>
        public static string PRIVATE_PROFILE {
            get {
                return ResourceManager.GetString("PRIVATE_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already a pro Member.
        /// </summary>
        public static string PRO_STATUS_ALREADY_GRANTED {
            get {
                return ResourceManager.GetString("PRO_STATUS_ALREADY_GRANTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratzzz {0}, you are now a pro member.
        /// </summary>
        public static string PRO_STATUS_GRANTED {
            get {
                return ResourceManager.GetString("PRO_STATUS_GRANTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was never pro.
        /// </summary>
        public static string PRO_STATUS_NEVER_GRANTED {
            get {
                return ResourceManager.GetString("PRO_STATUS_NEVER_GRANTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you are no longer a pro member.
        /// </summary>
        public static string PRO_STATUS_REMOVED {
            get {
                return ResourceManager.GetString("PRO_STATUS_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue cleared.
        /// </summary>
        public static string QUEUE_CLEARED {
            get {
                return ResourceManager.GetString("QUEUE_CLEARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string RATING {
            get {
                return ResourceManager.GetString("RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested by.
        /// </summary>
        public static string REQUESTED_BY {
            get {
                return ResourceManager.GetString("REQUESTED_BY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        public static string SEARCHING {
            get {
                return ResourceManager.GetString("SEARCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second(s).
        /// </summary>
        public static string SECOND_S {
            get {
                return ResourceManager.GetString("SECOND_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone is already tracking {0} ({1}) in {2}.
        /// </summary>
        public static string SOMEONE_ALREADY_TRACKING_IN_CHANNEL {
            get {
                return ResourceManager.GetString("SOMEONE_ALREADY_TRACKING_IN_CHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To go specific {0} search try adding &apos;{1}:&apos;before your search string. Eg: {2} {1}:Allen Walker.
        /// </summary>
        public static string SPECIFIC_SEARCHES_STRING {
            get {
                return ResourceManager.GetString("SPECIFIC_SEARCHES_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have successfully removed **{0}** ({1}) from your track list on this server..
        /// </summary>
        public static string SUCCESSFULLY_REMOVED_FROM_TRACKING_LIST {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_REMOVED_FROM_TRACKING_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string SUMMARY {
            get {
                return ResourceManager.GetString("SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamID.
        /// </summary>
        public static string TEAM_ID_STRING {
            get {
                return ResourceManager.GetString("TEAM_ID_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string TEAM_NAME {
            get {
                return ResourceManager.GetString("TEAM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Servers.
        /// </summary>
        public static string TOTAL_SERVERS {
            get {
                return ResourceManager.GetString("TOTAL_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users.
        /// </summary>
        public static string TOTAL_USERS {
            get {
                return ResourceManager.GetString("TOTAL_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already playing.
        /// </summary>
        public static string TRACK_ALTREADY_PLAYING {
            get {
                return ResourceManager.GetString("TRACK_ALTREADY_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track is seekable.
        /// </summary>
        public static string TRACK_IS_SEEKABLE {
            get {
                return ResourceManager.GetString("TRACK_IS_SEEKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search found no such tracks.
        /// </summary>
        public static string TRACK_NOT_FOUND {
            get {
                return ResourceManager.GetString("TRACK_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string TRACK_PAUSED {
            get {
                return ResourceManager.GetString("TRACK_PAUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Queue is Empty..
        /// </summary>
        public static string TRACK_QUEUE_EMPTY {
            get {
                return ResourceManager.GetString("TRACK_QUEUE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumed.
        /// </summary>
        public static string TRACK_RESUMED {
            get {
                return ResourceManager.GetString("TRACK_RESUMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped playing. Your queue is still intact though. Use &apos;{0}&apos; to Destroy the Queue.
        /// </summary>
        public static string TRACK_STOPPED_PLAYING {
            get {
                return ResourceManager.GetString("TRACK_STOPPED_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} songs in the queue.
        /// </summary>
        public static string TRACKS_IN_QUEUE {
            get {
                return ResourceManager.GetString("TRACKS_IN_QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not use this command at the moment. Reason: {0}.
        /// </summary>
        public static string UNMET_PRECONDITION_MESSAGE {
            get {
                return ResourceManager.GetString("UNMET_PRECONDITION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up next.
        /// </summary>
        public static string UP_NEXT {
            get {
                return ResourceManager.GetString("UP_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-time.
        /// </summary>
        public static string UP_TIME {
            get {
                return ResourceManager.GetString("UP_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url is not playable..
        /// </summary>
        public static string URL_NOT_PLAYABLE {
            get {
                return ResourceManager.GetString("URL_NOT_PLAYABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        public static string USAGE_STRING {
            get {
                return ResourceManager.GetString("USAGE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versus.
        /// </summary>
        public static string VERSUS {
            get {
                return ResourceManager.GetString("VERSUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume now is set to.
        /// </summary>
        public static string VOLUME_NOW_SET {
            get {
                return ResourceManager.GetString("VOLUME_NOW_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will be posting {0}&apos;s ({1}) new matches here in this channel every Hour.
        /// </summary>
        public static string WILL_BE_POSTING_USER_MATCHES_EVERY_HOUR {
            get {
                return ResourceManager.GetString("WILL_BE_POSTING_USER_MATCHES_EVERY_HOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win/Loss.
        /// </summary>
        public static string WIN_LOSS {
            get {
                return ResourceManager.GetString("WIN_LOSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Won.
        /// </summary>
        public static string WIN_PAST {
            get {
                return ResourceManager.GetString("WIN_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string WINS {
            get {
                return ResourceManager.GetString("WINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPM.
        /// </summary>
        public static string XPM {
            get {
                return ResourceManager.GetString("XPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay you are no longer {0}..
        /// </summary>
        public static string YOU_ARE_NO_LONGER_USER {
            get {
                return ResourceManager.GetString("YOU_ARE_NO_LONGER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t tracked **{0}** ({1}) on this server..
        /// </summary>
        public static string YOU_HAVE_NOT_TRACKED_USER {
            get {
                return ResourceManager.GetString("YOU_HAVE_NOT_TRACKED_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were never {0}..
        /// </summary>
        public static string YOU_WERE_NEVER_USER {
            get {
                return ResourceManager.GetString("YOU_WERE_NEVER_USER", resourceCulture);
            }
        }
    }
}
