//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkSide.Strings.Resources.Summaries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Summaries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Summaries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkSide.Strings.Resources.Summaries.Summaries", typeof(Summaries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares the bot summary here.
        /// </summary>
        public static string BOT_STATS {
            get {
                return ResourceManager.GetString("BOT_STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the queue.
        /// </summary>
        public static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very bad command. Dont ever use..
        /// </summary>
        public static string GIVE_DATABASE {
            get {
                return ResourceManager.GetString("GIVE_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists all the commands.
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero name or first few letters.
        /// </summary>
        public static string HERO_NAME_FIRST_LETTERS {
            get {
                return ResourceManager.GetString("HERO_NAME_FIRST_LETTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives you the target&apos;s hero list with specific performance..
        /// </summary>
        public static string HERO_RANKING {
            get {
                return ResourceManager.GetString("HERO_RANKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives your sad life a meaning. After you set this up, commands like &apos;profile&apos; and others wont require a parameter :).
        /// </summary>
        public static string I_AM {
            get {
                return ResourceManager.GetString("I_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will forget you and you will be cursed to give a parameter every-time you use an accountID demanding command..
        /// </summary>
        public static string I_AM_NOT {
            get {
                return ResourceManager.GetString("I_AM_NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides important links that can come in handly.
        /// </summary>
        public static string INVITE {
            get {
                return ResourceManager.GetString("INVITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the last match data for a steamID.
        /// </summary>
        public static string LAST_MATCH {
            get {
                return ResourceManager.GetString("LAST_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the bot&apos;s locale settings..
        /// </summary>
        public static string LOCALE {
            get {
                return ResourceManager.GetString("LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make someone pro user. Requires mention..
        /// </summary>
        public static string MAKE_PRO {
            get {
                return ResourceManager.GetString("MAKE_PRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives you detailed analysis of a specific match.
        /// </summary>
        public static string MATCH {
            get {
                return ResourceManager.GetString("MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more patch notes for you noob.
        /// </summary>
        public static string NO_PATCHES {
            get {
                return ResourceManager.GetString("NO_PATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the current playing song.
        /// </summary>
        public static string NOW_PLAYING {
            get {
                return ResourceManager.GetString("NOW_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sends you Dota 2 patches in this channel.
        /// </summary>
        public static string PATCHES {
            get {
                return ResourceManager.GetString("PATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauses the song.
        /// </summary>
        public static string PAUSE {
            get {
                return ResourceManager.GetString("PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returns the current estimated round-trip latency over WebSocket and REST&quot;.
        /// </summary>
        public static string PING {
            get {
                return ResourceManager.GetString("PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plays a song from tong of sources.
        /// </summary>
        public static string PLAY {
            get {
                return ResourceManager.GetString("PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes the bot&apos;s current prefix..
        /// </summary>
        public static string PREFIX {
            get {
                return ResourceManager.GetString("PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the target&apos;s current Profile with some nasty details.
        /// </summary>
        public static string PROFILE {
            get {
                return ResourceManager.GetString("PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints the current queue.
        /// </summary>
        public static string QUEUE {
            get {
                return ResourceManager.GetString("QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives you a list of the target&apos;s last 15 matches.
        /// </summary>
        public static string RECENT_MATCHES {
            get {
                return ResourceManager.GetString("RECENT_MATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke pro membership from someone. Requires mention..
        /// </summary>
        public static string REMOVE_PRO {
            get {
                return ResourceManager.GetString("REMOVE_PRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumes the song.
        /// </summary>
        public static string RESUME {
            get {
                return ResourceManager.GetString("RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeks to a particular position in the song (in sec).
        /// </summary>
        public static string SEEK {
            get {
                return ResourceManager.GetString("SEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skips the current playing song. Broken AF..
        /// </summary>
        public static string SKIP {
            get {
                return ResourceManager.GetString("SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the current playing song..
        /// </summary>
        public static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides important links that can come in handly.
        /// </summary>
        public static string SUPPORT {
            get {
                return ResourceManager.GetString("SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a hero&apos;s Talent Tree.
        /// </summary>
        public static string TALENTS {
            get {
                return ResourceManager.GetString("TALENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets a small profile for a pro Team.
        /// </summary>
        public static string TEAM {
            get {
                return ResourceManager.GetString("TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets the matches played by a pro team.
        /// </summary>
        public static string TEAM_MATCHES {
            get {
                return ResourceManager.GetString("TEAM_MATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name or Team ID.
        /// </summary>
        public static string TEAM_NAME_OR_ID {
            get {
                return ResourceManager.GetString("TEAM_NAME_OR_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the players of a pro team.
        /// </summary>
        public static string TEAM_PLAYERS {
            get {
                return ResourceManager.GetString("TEAM_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gives you a list of top professional teams sorted by their ratings..
        /// </summary>
        public static string TOP_TEAMS {
            get {
                return ResourceManager.GetString("TOP_TEAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start tracking a steamID.
        /// </summary>
        public static string TRACK {
            get {
                return ResourceManager.GetString("TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Tracking a steamID&apos;s games.
        /// </summary>
        public static string UNTRACK {
            get {
                return ResourceManager.GetString("UNTRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the volume for the current playing song 0-150.
        /// </summary>
        public static string VOLUME {
            get {
                return ResourceManager.GetString("VOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides important links that can come in handly.
        /// </summary>
        public static string VOTE {
            get {
                return ResourceManager.GetString("VOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s really a dumb thing for a human to ask a robot who he is.
        /// </summary>
        public static string WHO_AM_I {
            get {
                return ResourceManager.GetString("WHO_AM_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ill let you know who someone is if I know him.
        /// </summary>
        public static string WHO_IS {
            get {
                return ResourceManager.GetString("WHO_IS", resourceCulture);
            }
        }
    }
}
