//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkSide.Strings.Resources.Commands {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkSide.Strings.Resources.Commands.Commands", typeof(Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot Stats.
        /// </summary>
        public static string BOT_STATS {
            get {
                return ResourceManager.GetString("BOT_STATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string DISCONNECT {
            get {
                return ResourceManager.GetString("DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give database.
        /// </summary>
        public static string GIVE_DATABASE {
            get {
                return ResourceManager.GetString("GIVE_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero ranking.
        /// </summary>
        public static string HERO_RANKING {
            get {
                return ResourceManager.GetString("HERO_RANKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am.
        /// </summary>
        public static string I_AM {
            get {
                return ResourceManager.GetString("I_AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am not.
        /// </summary>
        public static string I_AM_NOT {
            get {
                return ResourceManager.GetString("I_AM_NOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string INVITE {
            get {
                return ResourceManager.GetString("INVITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Match.
        /// </summary>
        public static string LAST_MATCH {
            get {
                return ResourceManager.GetString("LAST_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale.
        /// </summary>
        public static string LOCALE {
            get {
                return ResourceManager.GetString("LOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make pro.
        /// </summary>
        public static string MAKE_PRO {
            get {
                return ResourceManager.GetString("MAKE_PRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        public static string MATCH {
            get {
                return ResourceManager.GetString("MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Patches.
        /// </summary>
        public static string NO_PATCHES {
            get {
                return ResourceManager.GetString("NO_PATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now playing.
        /// </summary>
        public static string NOW_PLAYING {
            get {
                return ResourceManager.GetString("NOW_PLAYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patches.
        /// </summary>
        public static string PATCHES {
            get {
                return ResourceManager.GetString("PATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PAUSE {
            get {
                return ResourceManager.GetString("PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string PING {
            get {
                return ResourceManager.GetString("PING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PLAY {
            get {
                return ResourceManager.GetString("PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string PREFIX {
            get {
                return ResourceManager.GetString("PREFIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string PROFILE {
            get {
                return ResourceManager.GetString("PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string QUEUE {
            get {
                return ResourceManager.GetString("QUEUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Matches.
        /// </summary>
        public static string RECENT_MATCHES {
            get {
                return ResourceManager.GetString("RECENT_MATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove pro.
        /// </summary>
        public static string REMOVE_PRO {
            get {
                return ResourceManager.GetString("REMOVE_PRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string RESUME {
            get {
                return ResourceManager.GetString("RESUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek.
        /// </summary>
        public static string SEEK {
            get {
                return ResourceManager.GetString("SEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string SKIP {
            get {
                return ResourceManager.GetString("SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string STOP {
            get {
                return ResourceManager.GetString("STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string SUPPORT {
            get {
                return ResourceManager.GetString("SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talents.
        /// </summary>
        public static string TALENTS {
            get {
                return ResourceManager.GetString("TALENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string TEAM {
            get {
                return ResourceManager.GetString("TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team-Matches.
        /// </summary>
        public static string TEAM_MATCHES {
            get {
                return ResourceManager.GetString("TEAM_MATCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team-Players.
        /// </summary>
        public static string TEAM_PLAYERS {
            get {
                return ResourceManager.GetString("TEAM_PLAYERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Teams.
        /// </summary>
        public static string TOP_TEAMS {
            get {
                return ResourceManager.GetString("TOP_TEAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string TRACK {
            get {
                return ResourceManager.GetString("TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untrack.
        /// </summary>
        public static string UNTRACK {
            get {
                return ResourceManager.GetString("UNTRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string UTILITIES {
            get {
                return ResourceManager.GetString("UTILITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string VOLUME {
            get {
                return ResourceManager.GetString("VOLUME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string VOTE {
            get {
                return ResourceManager.GetString("VOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who am I.
        /// </summary>
        public static string WHO_AM_I {
            get {
                return ResourceManager.GetString("WHO_AM_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who is.
        /// </summary>
        public static string WHO_IS {
            get {
                return ResourceManager.GetString("WHO_IS", resourceCulture);
            }
        }
    }
}
